// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sanuczpdqidzzcwzgxkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbnVjenBkcWlkenpjd3pneGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNjkzNjIsImV4cCI6MjA1MTY0NTM2Mn0.RD_bcJNKoxMxpO-6jISDeHGmlFMayRVFtG46dkDwews";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);